[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cl_ln = { path = "../cl_ln" }
regex = "1.9.6"
thiserror = "1.0.49"
